### ISSUE TITLE
依赖的转移，设计模式的良好运用。

### ISSUE THREAD

**Issue by MrPans** [youzan/SigmaTableViewModel#2]
SigmaTableViewModel 本质是：

将 UITableViewDataSource 对 **hard code** 的数字依赖转移成对 ViewModel 中**数组顺序**的依赖，并且将相同位置的 Cell 的相关信息和操作聚合在一处，便于管理。

对比系统的方式，代码量基本保持不变，可维护性大大增加。

Good !

**Comment by jackieyk** [comment]
:) 好久没更新了，最近会加一些新功能。
